### PR TITLE
Replace NSTimer-backed update mechanism with CADisplayLink for more reliable updates

### PR DESCRIPTION
**Pull request by natan**

### CODE REVIEW

**Comment by dataxpress** [comment]
I like this.

**Comment by natan** [comment]
@dataxpress Thanks! Would you consider tagging a new pod version with this change? I'd rather point to that (vs. `master`).

**Comment by dataxpress** [comment]
@natan Done! https://github.com/dataxpress/UICountingLabel/releases/tag/1.4.0

**Comment by natan** [comment]
@dataxpress Thank you!

**Comment by natan** [comment]
@dataxpress (As a reminder, you'll also need to `pod trunk push UICountingLabel.podspec` to finish publishing it).

**Comment by dataxpress** [comment]
Thanks, I appreciate it. Trunk has been updated.

**Pull request merged**
