### PR TITLE
Single Workspace Carthage Support + Project Rearrangement

### PR DESCRIPTION
**Pull request by SimonRice**
This PR rearranges the project to match the same layout generated via `pod lib create`, meaning the example & library projects are on a single workspace (& should work via `pod try` as well) - that in turn should address the issues highlighted in #38.  On the example project, I've also modernised the XIB (simply by opening it in Xcode 11), created a basic launch storyboard matching your old launch images & nudged the UI elements down by 20 pixels to cater for notches.

A positive (& intended) side effect of this is this adds Carthage support via the `_Pods.xcodeproj` project on the root directory, and I've tested this for both iOS & tvOS.

### CODE REVIEW

**Comment by dataxpress** [comment]
Let me know when you're ready for me to review this!

**Comment by SimonRice** [comment]
You're good to review this now 👍 just had a couple of minor corrections & cleanups earlier, but I'm done.

**Comment by dataxpress** [comment]
Okay, this looks mostly good to me, I'm not super familiar with Carthage so I can't speak to that, but just want to confirm that merging this won't break any existing Cocoapods installs right?

**Comment by SimonRice** [comment]
Good question @dataxpress - I've just given this a spin in an existing (currently CocoaPods based) project that uses this framework by having this entry in the Podfile:

```
pod 'UICountingLabel', git: 'https://github.com/SimonRice/UICountingLabel.git'
```

The project in question built without any issues and layout-wise it's as you'd expect too:

Screenshot 2019-11-14 at 7 15 40 pm

**However**, when doing final testing with Carthage, I found that my decision to gitignore `Example/Pods` broke the `_Pods.xcodeproj` symlink, so I've rolled this PR back by one commit, which will make it larger with mostly boilerplate stuff.

**Comment by dataxpress** [comment]
Without any time to properly test this on my own or review it in detail: LGTM, merging

**Pull request merged**
