### PR TITLE
Drop-in conversion to Swift 4+

### PR DESCRIPTION
**Pull request by Coeur**
- It keeps the exact same public objc interface as before, so `CTPViewController.m` works without a single character change.
- it's compatible Swift 3, Swift 4, Swift 4.2 and Swift 5.0.

### CODE REVIEW

**Comment by dataxpress** [comment]
I love this, but don't have time to review it right away - can anybody else provide some feedback or 👍? Otherwise, I'll spend some time on this soon but can't promise a specific date :-\

Thank you for the contribution!

**Comment by Coeur** [comment]
Let me help for the review, by providing a self-review.
I've just rebased to include the regex change from Master.

## 1. Interface
<kbd>cmd</kbd>-click on `#import <CountingTestProject-Swift.h>` will bring the auto-generated Obj-C interface from the swift file, which is now:

```
@interface UICountingLabel : UILabel
@property (nonatomic, copy) NSString * _Nonnull format;
@property (nonatomic) enum UILabelCountingMethod method;
@property (nonatomic) NSTimeInterval animationDuration;
@property (nonatomic, copy) NSString * _Nonnull (^ _Nullable formatBlock)(CGFloat);
@property (nonatomic, copy) NSAttributedString * _Nonnull (^ _Nullable attributedFormatBlock)(CGFloat);
@property (nonatomic, copy) void (^ _Nullable completionBlock)(void);
- (void)countFrom:(CGFloat)startValue to:(CGFloat)endValue;
- (void)countFrom:(CGFloat)startValue to:(CGFloat)endValue withDuration:(NSTimeInterval)duration;
- (void)countFromCurrentValueTo:(CGFloat)endValue;
- (void)countFromCurrentValueTo:(CGFloat)endValue withDuration:(NSTimeInterval)duration;
- (void)countFromZeroTo:(CGFloat)endValue;
- (void)countFromZeroTo:(CGFloat)endValue withDuration:(NSTimeInterval)duration;
- (CGFloat)currentValue SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, UILabelCountingMethod, closed) {
  UILabelCountingMethodEaseInOut = 0,
  UILabelCountingMethodEaseIn = 1,
  UILabelCountingMethodEaseOut = 2,
  UILabelCountingMethodLinear = 3,
  UILabelCountingMethodEaseInBounce = 4,
  UILabelCountingMethodEaseOutBounce = 5,
};
```

It's almost the same as before. The differences with the old `UICountingLabel.h` are:
- `format` is now `copy` instead of `strong`. This is because String in Swift is a struct, which is always copy-on-write. I would consider that as an improvement, as we don't need to worry about `format` being mutated while using it.
- `UICountingLabelFormatBlock` and `UICountingLabelAttributedFormatBlock` are not exposed anymore: sorry about that, I don't know if it's possible from Swift. If you want, we could temporary keep them in a .h file and mark them as deprecated.

## 2. Implementation

### `UILabelCountingMethod`
The enum uses camelCase to follow the Swift guidelines on naming conventions.
I've declared the `counter` as a private computed property to get a switch on `self` and to simplify the cyclomatic complexity of `count(from:to:withDuration:)`.

### `UICountingLabel(Attributed)FormatBlock`
**minor breaking change**. They are now Swift typealias instead of Objective-C typedef. I do not know if it's possible to expose them to Objective-C code. I didn't even made them public for Swift usage, as I hardly see the benefit here. If you want, we could add this `public` for the sole benefit of Swift users.

### `private extension RunLoopMode`
The essential of the file is written as if it was using the latest known Swift syntax (Swift 5). It works as well for Swift 4.2, but for older versions (Swift 3.0 and Swift 4.0) those 4 lines of code are a mini compatibility layer. Note that Apple made an announcement on [September 12th 2018](https://developer.apple.com/news/?id=09122018c) stating:
>Starting March 2019, all new apps and app updates for iPhone, including universal apps, will need to be built with the iOS 12 SDK

Which means that in the coming days (likely for the stable release of Xcode 10.2 and Swift 5), only Xcode 10.x will be allowed to publish iOS apps, so in theory we only really need to support Swift 4.2+ and there is no need to have this compatibility layer. We can remove it if you want.

### `kUILabelCounterRate`
**breaking change**. OK, similar problematic as the typealias, I don't know how to directly expose it to Objective-C. Indirectly, we could wrap it in an arbitrary class:
```
@objc public class kUILabelCounter: NSObject {
    @available(*, unavailable) override private init() { fatalError("unavailable") }
    @objc static var kUILabelCounterRate: CGFloat = 3.0
}
```
But that would be a lot of trouble for something that was only ever available as a MACRO definition previously. So for now I made it only visible from Swift.

### `UILabelCounter.update`
I declared the function static instead of instance, because there was no apparent use for instantiation.

### `UILabelCounterLinear`, etc.
I made them struct as they don't have any instance function or variable.
I replaced all the `powf(Double, Double) with `pow(CGFloat, CGFloat)`, which should only make a difference on 32 bits arch were it will perform the maths on Float values instead of Double values.

### `UICountingLabel`
Default values (format: "%f", method = .easeInOut, animationDuration = 2.0) were also the original values when previously calling `[label countFrom:0 to:0]`.

### `setTextValue`
I've opted to use the native Swift `String.range(of:options:)->Range?` instead of [the alternative from NSString](https://developer.apple.com/documentation/foundation/nsstring/1416849-range). One difference is that it can return nil, so I've tested it with `?.isEmpty == false` to cover both the case where it returns nil and the case where it returns an empty range.

### `runCompletionBlock`
I've removed the test on nil to simplify the readability.

### Overall
Superfluous parentheses and semi-colon were removed. Formatting was made as compliant as possible with default [SwiftLint](https://github.com/realm/SwiftLint) rules.

## Podspec
- `s.exclude_files` seems to point to a non-existing folder, so I've removed it.
- `s.requires_arc` is superfluous, as the default value is already `true`, so I've removed it.
- I've removed `{h,m}` to make sure it's pure swift, but if you want a layer for instance to deprecate `UICountingLabelFormatBlock` in objc, then we'll need to include `{h,swift}`.
- Once CocoaPods 1.7.0 STABLE is released, we can add `s.swift_versions = ['3.0', '4.0', '4.2', '5.0']`. But don't add it before the final release of CocoaPods 1.7.0, otherwise many people will be unable to install the pod. No need to add `s.swift_version` in the meantime: it would be superfluous.

## Example target
- Bridging-Header.h is required to expose the Swift code.
- CTPViewController.xib had to be updated because it was in a super old format where `UICountingLabel` was previously explicitly referring to the `.h` file.
- The rest is untouched, which demonstrates that it's a drop-in replacement.

**Comment by Coeur** [comment]
Sorry, I don't feel like redoing it that pull request after the reorganization of the repository a couple of days ago. I guess that you may solve the conflicts yourself or close the pull request.

**Comment by dataxpress** [comment]
Hey, totally understood. Thanks for all your effort anyway!

**Pull request closed without merging**
