### PR TITLE
Rewrite UICountingLabel to swift language

### PR DESCRIPTION
**Pull request by Reskov**
Also fixed small issue in regex pattern, you have been missing NSRegularExpressionSearch at second search

### CODE REVIEW

**Comment by dataxpress** [comment]
I like the fix on the regex, but I think a Swift rewrite is a bit premature, as Swift is still a bit unstable and has more changes on the horizon. An Objective-C library will work well with a Swift project, but adding a Swift library to an otherwise Objective-C project really dramatically increases the app size (because of the need to bundle the Swift runtime).

**Comment by ryancoughlin** [comment]
Thoughts on revisiting this now?

**Comment by codeHatcher** [comment]
+1

**Comment by f8th** [comment]
EyreFree has done a simplified version of UICountingLabel in Swift : https://github.com/EyreFree/UICountingLabel

I have just added Animation Curves this morning (Linear, EaseIn, EaseOut and EaseInOut), should I create a new branch here or just update it on EyreFree ? My implementation differs slightly from the original UICountingLabel, as I preferred using a property instead of making distinct objects for each curve : 
`var animationCurve: UICountingLabelAnimationCurve = .Linear`

**Comment by codeHatcher** [comment]
Wow! Awesome!

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Fri, Feb 26, 2016 at 7:57 AM, David Pelletier <notifications@github.com>
wrote:
EyreFree has done a simplified version of UICountingLabel in Swift : https://github.com/EyreFree/UICountingLabel
[https://github.com/EyreFree/UICountingLabel]

I have just added Animation Curves this morning (Linear, EaseIn, EaseOut and
EaseInOut), should I create a new branch here or just update it on EyreFree ? My
implementation differs slightly from the original UICountingLabel, as I
preferred using a property instead of making distinct objects for each curve :
var animationCurve: UICountingLabelAnimationCurve = .Linear

—
Reply to this email directly or view it on GitHub
[https://github.com/dataxpress/UICountingLabel/pull/30#issuecomment-189263900] .[https://github.com/notifications/beacon/AFHNVpJodqrvxjeKHfVOMR1jUc9081Ynks5poEM_gaJpZM4DfWbx.gif]

**Comment by ryancoughlin** [comment]
@dataxpress Thoughts on pushing this Swift build forward? Swift is making great headway and much more stable, this is also a much smaller library so worrying about compiling shouldn't be an issue

**Comment by ryancoughlin** [comment]
If not, @Reskov would you consider creating a new repo and a Carthage source for this?

**Comment by Mar-k** [comment]
I've updated EyreFrees answer to Swift 3.0

https://gist.github.com/Mar-k/2b4e55cd92eb52809a9110ab34289161

**Comment by EyreFree** [comment]
The lastest code in Swift is here:

https://github.com/EyreFree/EFCountingLabel

🤔, if any problem, tell me.

**Comment by acumen1005** [comment]
i also rewrite UICountingLabel for swift , welcome to review

https://github.com/acumen1005/ACLabelCounting

**Comment by Coeur** [comment]
@Reskov thank you, but your Pull Request being a bit outdated, I've re-done it from scratch at #63:
- fully compatible Objective-C, Swift 3, 4, 4.2, 5.0.
- got all the enum cases up-to-date
- doesn't alter the existing regexp (as that should be a matter of a separate pull request)
- drop-in replacement: people can pod update UICountingLabel without noticing it's now swift-based.

@acumen1005 thanks for ACLabelCounting.

@EyreFree thanks for EFCountingLabel, I bet you got the most popular repository nowadays.

**Comment by onursahindur** [comment]
**Note that** 
If you use _both obj-c and swift in your code_ **EFCountingLabel fails** since it has **no Obj-C support**

From 2020, anyone wants to find a swift version of UICountingLabel, 
you can use it with swift bridges. 
More information here:
https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift


The most challenging part is to rewrite formatBlock but I managed to do it in swift.

You may use for formatBlock;

    myLabel.formatBlock = { (value) -> Optional<String> in
         return String(format: "+%.0f", value)
    }

You may use for counting with duration;

    myLabel.count(from: 0, to: 100, withDuration: 1)


Cheers.

**Pull request closed without merging**
